# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 544c5c1b71d459dd7656a59e1a9ac631bb310248355e87c60aa85540fafcd458d7049cd31e184e441896e126149b502d07397f379bd5344352c3e55dd836375c

test:
  secret_key_base: d8b1251b470d4003fba04241d1708eb9efd654cb3e8481dcd7eb6cf6434745ca1d27ccf48847dfe3c2f591fd1c7fc3b9e566169eb8a64a0040e4ab0edb75747a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
